plugins {
    id 'base'
}

group = 'com.s1000Dorg.viewer'
version = '0.1.0'

allprojects {
    group = rootProject.group
    version = rootProject.version
    repositories {
        mavenCentral()
    }
}

tasks.register('cleanAll') {
    dependsOn ':application:clean', ':webapp:clean'
}

tasks.named('clean') {
    dependsOn 'cleanAll'
}
