CREATE TABLE dm (
  dm_id VARCHAR2(255) PRIMARY KEY,
  display_name VARCHAR2(500),
  model_ident VARCHAR2(100),
  system_code VARCHAR2(50),
  info_code VARCHAR2(50),
  language_code VARCHAR2(10),
  issue_number VARCHAR2(10),
  in_work VARCHAR2(10),
  vault_path VARCHAR2(1000) NOT NULL,
  file_hash VARCHAR2(128),
  aircraft_tags CLOB,
  engine_tags CLOB,
  variant_tags CLOB,
  last_indexed TIMESTAMP
);

CREATE TABLE pmc (
  pmc_id VARCHAR2(255) PRIMARY KEY,
  title VARCHAR2(500),
  vault_path VARCHAR2(1000) NOT NULL,
  file_hash VARCHAR2(128),
  last_indexed TIMESTAMP
);

CREATE TABLE pmc_dm (
  pmc_id VARCHAR2(255) NOT NULL,
  dm_id VARCHAR2(255) NOT NULL,
  sort_order NUMBER,
  PRIMARY KEY (pmc_id, dm_id),
  CONSTRAINT fk_pmc_dm_pmc FOREIGN KEY (pmc_id) REFERENCES pmc (pmc_id),
  CONSTRAINT fk_pmc_dm_dm FOREIGN KEY (dm_id) REFERENCES dm (dm_id)
);

CREATE TABLE icn (
  icn_id VARCHAR2(255) PRIMARY KEY,
  vault_path VARCHAR2(1000) NOT NULL,
  type VARCHAR2(20),
  file_hash VARCHAR2(128),
  last_indexed TIMESTAMP
);

CREATE TABLE dm_icn (
  dm_id VARCHAR2(255) NOT NULL,
  icn_id VARCHAR2(255) NOT NULL,
  PRIMARY KEY (dm_id, icn_id),
  CONSTRAINT fk_dm_icn_dm FOREIGN KEY (dm_id) REFERENCES dm (dm_id),
  CONSTRAINT fk_dm_icn_icn FOREIGN KEY (icn_id) REFERENCES icn (icn_id)
);

CREATE TABLE audit_event (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  username VARCHAR2(255),
  action VARCHAR2(100),
  dm_id VARCHAR2(255),
  details_json CLOB
);

CREATE INDEX idx_dm_last_indexed ON dm (last_indexed);
CREATE INDEX idx_dm_hash ON dm (file_hash);
CREATE INDEX idx_pmc_last_indexed ON pmc (last_indexed);
CREATE INDEX idx_pmc_hash ON pmc (file_hash);
CREATE INDEX idx_pmc_dm_dm ON pmc_dm (dm_id);
CREATE INDEX idx_icn_type ON icn (type);
CREATE INDEX idx_icn_hash ON icn (file_hash);
CREATE INDEX idx_dm_icn_icn ON dm_icn (icn_id);
CREATE INDEX idx_audit_action_ts ON audit_event (action, ts);
